services:
  postgres:
    image: postgres:17
    container_name: linguaclass-p3-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lingua
      POSTGRES_PASSWORD: lingua
      POSTGRES_DB: linguaclass_p3
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_p3:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: linguaclass-p3-mailhog
    restart: unless-stopped
    ports:
      - "1027:1025"
      - "8027:8025"

volumes:
  postgres_data_p3:
